---
  - name: Playbook for installing Docker and Java on the agent nodes
    hosts: instances
    remote_user: ubuntu
    tasks:
      - name: Install dependencies for Docker repository
        apt:
          name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'openjdk-8-jre-headless', 'aptitude', 'python-minimal', 'awscli' ]
          update_cache: yes
        become: true

      - name: Add apt key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: "present"
        become: true
      
      - name: Add Docker repository
        apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          state: "present"
        become: true
        
      - name: Install Docker
        apt:
          name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
          state: "present"
          update_cache: yes
        become: true
      
      - name: Create Jenkins directory
        file:
          path: "/opt/jenkins/"
          owner: "ubuntu"
          group: "ubuntu"
          state: "directory"
        become: yes

      - name: Start Docker Engine
        systemd:
          name: docker
          daemon_reload: yes
          state: "restarted"
          enabled: yes
          masked: no
        become: true

      - name: Add user to Docker group
        user:
          name: ubuntu
          append: yes
          groups: [ 'docker' ]
        become: true

      - name: Install Cronjob for cleaning old images
        cron:
          state: "present"
          user: "ubuntu"
          minute: "53"
          hour: "23"
          name: "Cronjob for cleaning Docker image cache"
          job: "docker builder prune --force --filter until=24h && docker rmi $(docker images -q -f dangling=true)"