name: Jenkins Docker Image

on:
  push:
    branches: [ master ]
    paths: [ '**/Dockerfile', '**/jenkins.yaml' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./jenkins --file jenkins/Dockerfile --tag jenkins:latest
      
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
    - name: Push to ECR
      run: |
        docker tag jenkins ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/jenkins:latest
        docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/jenkins:latest