name: Sonarqube Docker Image

on:
  push:
    branches: [ master ]
    paths: [ 'sonarqube/Dockerfile', '**/sonar.properties' ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        cd sonarqube/
        docker build --tag sonarqube:latest .

    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1

    - name: Push to ECR
      run: |
        docker tag sonarqube ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/sonarqube:latest
        docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/sonarqube:latest